name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: Config git
        run: |
          git config --global user.email "christophe.blefari@gmail.com"
          git config --global user.name "Christophe Blefari"
      - run: npm install --include dev
      - run: npm run build
        env:
          PUBLIC_URL: "https://www.qrators.io/datacouncil"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
